fixes symbols conflict with libaom.  (#1329)
* build: fix conflics with libaom.

if we enable libaom and libsvtav1 at same time in ffmpeg like this
./configure --enable-libsvtav1 --enable-libaom

it will report error:
libSvtAv1Enc.so: warning: multiple common of `aom_obmc_variance32x32'
libaom.a(aom_dsp_rtcd.c.o): warning: previous common is here
libSvtAv1Enc.so: warning: multiple common of `av1_build_compound_diffwtd_mask'
libaom.a(av1_rtcd.c.o): warning: previous common is here

The root cause is we reuse some functions in libaom. Make it hidden by default will fix the issue

* build: fix build for gcc 7.5

gcc 7.5 will report following error:

/home/runner/work/SVT-AV1/SVT-AV1/Source/Lib/Common/Codec/EbBitstreamUnit.c: In function ‘eb_aom_daala_stop_encode’:
/home/runner/work/SVT-AV1/SVT-AV1/Source/Lib/Common/Codec/EbBitstreamUnit.c:75:14: error: ‘daala_bytes’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

* symbols: refact, use EB_API to define the dynamic symbol export